"""Update user model for email verification

Revision ID: bc6b7b5f513f
Revises: 5aaaa1fcfef0
Create Date: 2026-09-29 21:44:56.172881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6b7b5f513f'
down_revision: Union[str, Sequence[str], None] = '5aaaa1fcfef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('parent_case_id', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('assessment', sa.String(), nullable=False),
    sa.Column('authenticity_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('confidence_level', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_demo_analysis', sa.Boolean(), nullable=True),
    sa.Column('disclaimer', sa.String(), nullable=True),
    sa.Column('ai_generation_probability', sa.Float(), nullable=False),
    sa.Column('manipulation_risk', sa.Float(), nullable=False),
    sa.Column('forensic_anomaly_score', sa.Float(), nullable=False),
    sa.Column('metadata_risk_score', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('evidence_breakdown', sa.JSON(), nullable=True),
    sa.Column('metadata_analysis', sa.JSON(), nullable=True),
    sa.Column('suspicious_regions', sa.JSON(), nullable=True),
    sa.Column('suspicious_segments', sa.JSON(), nullable=True),
    sa.Column('text_metrics', sa.JSON(), nullable=True),
    sa.Column('heatmap_data', sa.JSON(), nullable=True),
    sa.Column('why_result_explanation', sa.String(), nullable=True),
    sa.Column('top_contributing_signals', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_case_id'), 'investigations', ['case_id'], unique=True)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token_expires_at')
    op.drop_column('users', 'verification_token_hash')
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_investigations_case_id'), table_name='investigations')
    op.drop_table('investigations')
    # ### end Alembic commands ###
